version: '3'

services:
  db:
    restart: always
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: neighbor
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "1234:5432"

volumes:
  data:
